export MTK_PLATFORM_VERSION := mt6985

obj-m += mali_valhall/mali-r43p0/drivers/gpu/arm/midgard/
obj-m += mali_valhall/mali-r43p0/drivers/base/arm/memory_group_manager/
obj-m += mali_valhall/mali-r43p0/drivers/base/arm/protected_memory_allocator/
