export MTK_PLATFORM_VERSION := mt6989

obj-m += mali_avalon/mali-r44p0/drivers/gpu/arm/midgard/
obj-m += mali_avalon/mali-r44p0/drivers/base/arm/memory_group_manager/
obj-m += mali_avalon/mali-r44p0/drivers/base/arm/protected_memory_allocator/
